In [1]:
import numpy as np
import profile
def encoding(input):
    list=[0,2,4,8,16,32,64,128,256,512,1024,2048,4096,8192,16384,32768]
    code=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    output=np.zeros((4,4),dtype=int)
    for i in code:
        output[np.where(input==list[i])]=code[i]
    return output

def generate_sequence(i):
    np.random.seed()
    X_in=np.empty((saved_steps,4,4),dtype=int)
    mask=np.zeros((saved_steps),dtype=bool)
    #X_reg=np.empty((steps,4,4),dtype=float)
    Y_in=np.empty((saved_steps),dtype=int)
    game = Game(4, random=False)
    agent = ExpectiMaxAgent(game)
    save_id=0
    for j in range(steps):
        t=agent.step()
        #if j<1000 or j%sample_every_n_steps==0:
        X_in[save_id,0:4,0:4]=encoding(agent.game.board)
        Y_in[save_id]=t;
        mask[save_id]=True
        save_id+=1
            #X_in[j,0:4,0:4]=encoding(agent.game.board)
            #X_reg[j,0:4,0:4]=X_in[j,0:4,0:4]/np.max(X_in[j,0:4,0:4])
        agent.game.move(t)
        if agent.game.end:
            print ("bad",j)
            break     
    print (i)
    return X_in,Y_in,mask

In [ ]:
import multiprocessing
from multiprocessing.pool import ThreadPool
import time
from game2048.game import Game
from game2048.agents import ExpectiMaxAgent

steps=1000
sample_every_n_steps=1

def get_seqlength():
    i=0
    for j in range(steps):
        if j<1000 or j%sample_every_n_steps==0:
            i+=1
    return i

saved_steps=get_seqlength()
print (saved_steps)
numsample=55
nfiles=10000
save_directory="data/"
items = [x for x in range(0, numsample)]
p = multiprocessing.Pool(55)

import os.path
if os.path.isfile("currentfileindex.npy"):
    startfileindex=np.load("currentfileindex.npy")
    filenamelist=np.load("filenamelist.npy").tolist()
else:
    startfileindex=0
    filenamelist=[]
    
#p = ThreadPool(10)
for fileid in range(startfileindex,nfiles+startfileindex):
    filenamelist.append([save_directory+"X_"+str(fileid)+'.npy',save_directory+"Y_"+str(fileid)+'.npy'
                         ,save_directory+"Mask_"+str(fileid)+'.npy'])
    X=np.zeros((numsample,saved_steps,4,4),dtype=int)
    #X_reg=np.empty((numsample,steps,4,4),dtype=float)
    mask=np.zeros((numsample,saved_steps),dtype=bool)
    Y=np.zeros((numsample,saved_steps),dtype=int)
    
    ans= p.map(generate_sequence, items)
    
#     p.join()
    for i in range(0,numsample):
        X[i]=ans[i][0]
        #X_reg[i]=ans[i][1]
        Y[i]=ans[i][1]
        mask[i]=ans[i][2]
    np.save(filenamelist[fileid][0],X)
    np.save(filenamelist[fileid][1],Y)
    np.save(filenamelist[fileid][2],mask)
    np.save("currentfileindex.npy",fileid+1)
    np.save("filenamelist",filenamelist)
    print ("end one file")

p.close()
p.join()

1000
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loaded expectmax lib for 2048: /home/woaiwinnie2/2048-api/game2048/expectimax/bin/2048.so
Loade

In [4]:
import os.path
if os.path.isfile("currentfileindex.npy"):
    startfileindex=np.load("currentfileindex.npy")
    filenamelist=np.load("filenamelist.npy")
else:
    startfileindex=0
    filenamelist=[]
print (startfileindex,filenamelist)

1 [['data/X_0' 'data/Y_0' 'data/Mask_0']
 ['data/X_1' 'data/Y_1' 'data/Mask_1']
 ['data/X_2' 'data/Y_2' 'data/Mask_2']
 ['data/X_3' 'data/Y_3' 'data/Mask_3']
 ['data/X_4' 'data/Y_4' 'data/Mask_4']
 ['data/X_5' 'data/Y_5' 'data/Mask_5']
 ['data/X_6' 'data/Y_6' 'data/Mask_6']
 ['data/X_7' 'data/Y_7' 'data/Mask_7']
 ['data/X_8' 'data/Y_8' 'data/Mask_8']
 ['data/X_9' 'data/Y_9' 'data/Mask_9']
 ['data/X_10' 'data/Y_10' 'data/Mask_10']
 ['data/X_11' 'data/Y_11' 'data/Mask_11']
 ['data/X_12' 'data/Y_12' 'data/Mask_12']
 ['data/X_13' 'data/Y_13' 'data/Mask_13']
 ['data/X_14' 'data/Y_14' 'data/Mask_14']
 ['data/X_15' 'data/Y_15' 'data/Mask_15']
 ['data/X_16' 'data/Y_16' 'data/Mask_16']
 ['data/X_17' 'data/Y_17' 'data/Mask_17']
 ['data/X_18' 'data/Y_18' 'data/Mask_18']
 ['data/X_19' 'data/Y_19' 'data/Mask_19']]


In [15]:
nfiles=1000
filenamelist=[]
save_directory="data/"
for i in range(nfiles):
    filenamelist.append([save_directory+"X_"+str(i),save_directory+"Y_"+str(i),save_directory+"Mask_"+str(i)])
filenamelist[0][0]
np.save(filenamelist[0][0],filenamelist)

In [ ]:
steps=500
profile.run('generate_sequence(0)')

In [ ]:
X[0]

In [ ]:
X_reg=np.empty((10000,400,4,4),dtype=float)
for i in range(0,10000):
    for j in range(0,400):
        X_reg[i,j]=X[i,j,0:4,0:4]/np.max(X[i,j,0:4,0:4])

In [ ]:
np.save("X.npy",X)
np.save("Y.npy",Y)
np.save("mask.npy",mask)
#np.save("X_reg.npy",X_reg)

In [20]:
X=np.load("data/Y_0.npy")
X[1][1650:1700]

bad [[3 1 3 ... 0 0 0]
 [3 1 3 ... 0 0 0]
 [3 1 3 ... 0 0 0]
 ...
 [3 1 3 ... 0 0 0]
 [3 1 3 ... 0 0 0]
 [3 1 3 ... 0 0 0]]
